// Array<["내장 태그","변경될 class name"]>

export const compileKeywords: Array<[string,string]> = [
    ["ChatTopMainTitleText",".css-1nc12v8"],
    ["ChatTopMainTitle",".css-xhmj3v"],
    ["ChatTopMain",".css-10ht3ww"],
    ["ChatTopSuperchatText",".css-8m2xpx"],
    ["ChatTopSuperchat",".css-1efa1bt"],
    ["ChatTopMenuIconDarkInActive",".css-1m49n3z"],
    ["ChatTopMenuIconWhiteInActive",".css-1vdwgf2"],
    ["ChatTopMenuIconDarkActive",".css-18fxgs5"],
    ["ChatTopMenuIconWhiteActive",".css-yyirp"],
    ["ChatTop",".css-6g3r0p"],
    ["ChatBackground",".css-nl42z7, .css-dfg942"],
    ["ChatBarText",".css-1ognqe, .css-1fzuctd, .css-izb7yb, .css-15vkk13"],
    ["ChatMenusButtonText",".css-15eskfn"],
    ["ChatMenusButtonWhite",".css-h3d181"],
    ["ChatMenusButtonDark",".css-k4ctzz"],
    ["ChatMenuNewstartSelectText",".css-12c3ers"],
    ["ChatMenuNewstartSelect",".css-c4o7wp"],
    ["ChatMenuNewstartButtonText",".css-18na997"],
    ["ChatMenuNewstartButton",".css-1rcb6gt"],
    ["ChatMenuNewstart",".css-dntxqc, .css-3qxgfb"],
    ["ChatMenus",".css-j7qwjs"],
    ["ChatMenuText",".css-uhb2yf"],
    ["ChatMenu",".css-3nlmbp, .css-1jh10ze, .css-fm3cmg, .css-1gqdld2"],
    ["ChatBar",".css-1e28b1b, .css-1rvkdkw"],
    ["ChatCharacterTextInTwostar",".css-q6mb20"],
    ["ChatCharacterTextInstar",".css-ssrqv0"],
    ["ChatCharacterText",".css-1iz5lr1"],
    ["ChatCharacterRightspace",".css-yz8nv"],
    ["ChatCharacterSuperchat",".css-1wmi91f"],
    ["ChatCharacter",".css-1m1tbv5"],
    ["ChatUserTextInTwostar","css-rthce9"],
    ["ChatUserTextInstar","css-12gpcg1"],
    ["ChatUserText",".css-130mhiw"],
    ["ChatUserBox",".css-1k5k8hb"],
    ["ChatUser",".css-1oikzkj"],
    ["SideMenusText",".css-9yvi50"],
    ["SideMenusExtIconInActive",".css-38wt0x"],
    ["SideMenusExtIconActive",".css-44d0y5"],
    ["SideMenusExt",".css-18jqfyr"],
    ["SideMenus",".css-0"],
    ["SideMenuRecentlyText",".css-p55s5a"],
    ["SideMenuRecently",".css-wp2yb2"],
    ["SideMenuUserInActive",".css-1eixg46"],
    ["SideMenuUserActive",".css-o4pavp"],
    ["SideMenuIconInActive",".css-1lzn2lu"],
    ["SideMenuIconActive",".css-b6x1g0"],
    ["SideMenuIn",".css-1t6boja"],
    ["SideMenu",".css-1oqkloy, .css-1keu2s9, .css-1t6boja"],
    ["SideChatroomTopTitleText",".css-9yvi50"],
    ["SideChatroomTopClose",".css-skmmw2"],
    ["SideChatroomTopEditText",".css-1t02qjb"],
    ["SideChatroomTopEdit",".css-15rgam7"],
    ["SideChatroomTop",".css-16oohbe, .css-189vsrq"],
    ["SideChatroomsInActive",".css-1rx1zwc"],
    ["SideChatroomsActive",".css-14k2xlu"],
    ["SideChatroomsMyCharacterInActive",".css-7ftrsz"],
    ["SideChatroomsMyCharacterActive",".css-1y4mpkb"],
    ["SideChatroomsTitleText",".css-1hxajdh"],
    ["SideChatroomsTopicText",".css-14lxmf"],
    ["SideChatrooms",".css-iflvni"],
    ["SideChatroom",".css-oll1f7, .css-1hbv8bi"],
    ["SideWrtnIcon",".css-1di1j86"],
    ["ChatSuperchat",".css-15z17ag"],
    ["Chat",".css-7ehegr"],
]